title: Machine Learning School for Toxinologists 2023
description: > # this means to ignore newlines until "show_excerpts:"
  Machine Learning School for Toxinologists, Bioligists.
  We will teach the basics of machine learning with biological data.
baseurl: "/"
url: https://mlschool23.rostlab.org/

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  persons:
    output: false
  questions:
    output: false
  program:
    output: true
    permalink: "/:collection/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  uglifier_args:
    harmony: true

twitter:
  card: summary_large_image

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor

form_url: "https://wiki.tum.de/display/rostlabform/Summer+School+Registration"
